service: prisma-serverless

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  stage: ${opt:stage}
  serverless-offline:
    port: 1337
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'yarn' # Reserved for future use. Any other values will not work right now.
    packExternalModulesMaxBuffer: 204800 # Size of stdio buffers for spawned child processes

provider:
  name: aws
  runtime: nodejs8.10
  cfLogs: true
  region: ap-southeast-2
  environment: ${file(./config/env.yml)}

package:
  individually: true

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: /
          method: get
          cors: true
          integration: lambda-proxy
